title: HORSE
description: Welcome to my personal space on the web!

author:
  name: Harish sarma
  url: #https://harishsarmatr.github.io/Horse/

owner: Thomsonreuters
year: 2024

theme: jekyll-theme-cayman
markdown: kramdown
