title: Horse
description: Hi my name is Jhonny, please feel free to navigate to know about me!

author:
  name: Harish sarma
  url: #https://harishsarmatr.github.io/Horse/

owner: Thomsonreuters
year: 2024

google_analytics: false
theme: jekyll-theme-minimal
